framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            rabbitmq:
                dsn: "amqp://guest:guest@rabbitmq-management/%2f"
                # failed: 'doctrine://default?queue_name=failed'
                # sync: 'sync://'
                options:
                    # Messenger will create then send to this exchange
                    exchange:
                        name: messages2
                        type: fanout
                        default_publish_routing_key: normal
                    # Messenger will create this queue & add binding keys
                    # The worker will know to consume from this queue
                    queues:
                        messages_normal:
                            binding_keys: [normal]

        routing:
            # rabbitmq is whatever name you gave your transport above
            'App\Controller\*': rabbitmq
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
